<a href="https://colab.research.google.com/github/ChauDucToan/NLP/blob/main/2351050182_ChauDucToan_BTH1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bài thực hành tại lớp
**Họ và tên**: Châu Đức Toàn

**Lớp**: DS2301

**MSSV**: 2351050182

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

print(f'Pytorch version: {torch.__version__}')

Pytorch version: 2.10.0+cu128


# 1. Tensor

## 1.1 Khởi tạo một tensor

In [4]:
x = torch.tensor([1, 2, 3, 4])
print(f'Tensor 1D: {x}')

Tensor 1D: tensor([1, 2, 3, 4])


In [3]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f'Tensor 2D: {matrix}')

Tensor 2D: tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
float_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(f'Float tensor: {float_tensor}')

Float tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
int_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.int64)
print(f'Int tensor: {int_tensor}')

Int tensor: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [10]:
zeros = torch.zeros(3, 4)
print(f'Zero tensor with matrix 3x4: {zeros}')

Zero tensor with matrix 3x4: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
ones = torch.ones(2, 3)
print(f'One tensor with matrix 2x3: {ones}')

One tensor with matrix 2x3: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
rand = torch.rand(2,2)
randn = torch.randn(2,3)

print(f"Uniform distribution tensor: {rand}")
print(f"Normal distribution tensor: {randn}")

Uniform distribution: tensor([[0.5253, 0.1365],
        [0.8493, 0.8700]])
Normal distribution: tensor([[-0.4755,  0.0676,  1.0622],
        [-2.5031,  1.1012, -0.0884]])


In [15]:
range_tensor = torch.arange(0, 10, step=1)
linspace = torch.linspace(0, 10, steps=20)

print(f'Range tensor: {range_tensor}')
print(f'Linear space tensor: {linspace}')

Range tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Linear space tensor: tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])


## 1.2 Tensor Attributes

In [19]:
x = torch.randn(2, 3, 4)
print(f'Tensor 3d:\n{x}')
print(f'Tensor shape: {x.shape}')
print(f'Tensor size: {x.size()}')
print(f'Number of dimensions: {x.dim()}')
print(f'Tensor data type: {x.dtype}')
print(f'Device: {x.device}')

Tensor 3d:
tensor([[[-0.6216,  1.1699,  0.6734, -0.0228],
         [ 0.0870, -0.5471,  1.3816, -0.3115],
         [-1.5921,  0.4074, -0.3518, -0.1113]],

        [[-2.1492, -3.0325,  2.2726, -0.4086],
         [-0.0552,  1.1383, -0.6818,  0.0126],
         [ 1.2724,  2.3026, -0.6320, -1.1635]]])
Tensor shape: torch.Size([2, 3, 4])
Tensor size: torch.Size([2, 3, 4])
Number of dimensions: 3
Tensor data type: torch.float32
Device: cpu


## 1.3 Tensor Indexing and Slicing

In [20]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Original tensor:\n{x}')

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [21]:
print('Indexing:')
print(f"x[0, 0] = {x[0, 0]}")
print(f"x[1, 2] = {x[1, 2]}")

Indexing:
x[0, 0] = 1
x[1, 2] = 6


In [24]:
print("Slicing:")
print(f'First column:\n{x[:, 0]}')
print(f'First column:\n{x[1, :]}')
print(f'Sub-matrix 2x2:\n{x[0:2, 1:3]}')

Slicing:
First column:
tensor([1, 4, 7])
First column:
tensor([4, 5, 6])
Sub-matrix 2x2:
tensor([[2, 3],
        [5, 6]])


In [35]:
x = torch.randn(3,4,5)
print(f'Tensor 3d:\n {x}')

Tensor 3d:
 tensor([[[-0.2970,  0.9433,  0.5270,  1.2860, -0.5153],
         [-0.0288, -1.0319, -2.2082, -0.0534,  0.8512],
         [ 0.2984,  0.7496,  0.1125, -0.0123,  0.4029],
         [-0.3214, -1.1227,  0.7858,  1.2082, -1.2772]],

        [[-0.1108,  0.9461, -0.0023, -1.7337,  0.1216],
         [-0.0966,  0.7608,  1.2792,  0.6641,  0.2523],
         [-0.9574,  0.6214, -0.6679,  0.1328,  0.1420],
         [-0.6405, -1.0414,  0.0900, -0.7561, -0.0167]],

        [[-0.0488,  1.0445, -1.8624,  0.0789, -0.0042],
         [-0.3636,  0.1504,  1.5381, -0.1029, -0.4422],
         [-0.6178,  0.5318, -0.1773,  0.6662, -0.1217],
         [ 0.1538,  0.3936,  1.5971, -0.0379,  0.3209]]])


In [ ]:
print(f'Slicing Tensor:\n{x[0]}')

Slicing Tensor:
tensor([[-0.2970,  0.9433,  0.5270,  1.2860, -0.5153],
        [-0.0288, -1.0319, -2.2082, -0.0534,  0.8512],
        [ 0.2984,  0.7496,  0.1125, -0.0123,  0.4029],
        [-0.3214, -1.1227,  0.7858,  1.2082, -1.2772]])


In [39]:
print(x[0, 0])

tensor([-0.2970,  0.9433,  0.5270,  1.2860, -0.5153])


In [40]:
indicies = torch.tensor([0, 2])
print(f'Indexing with another tensor:\n{x[indicies]}')

Indexing with another tensor:
tensor([[[-0.2970,  0.9433,  0.5270,  1.2860, -0.5153],
         [-0.0288, -1.0319, -2.2082, -0.0534,  0.8512],
         [ 0.2984,  0.7496,  0.1125, -0.0123,  0.4029],
         [-0.3214, -1.1227,  0.7858,  1.2082, -1.2772]],

        [[-0.0488,  1.0445, -1.8624,  0.0789, -0.0042],
         [-0.3636,  0.1504,  1.5381, -0.1029, -0.4422],
         [-0.6178,  0.5318, -0.1773,  0.6662, -0.1217],
         [ 0.1538,  0.3936,  1.5971, -0.0379,  0.3209]]])


In [43]:
mask = x > 0.5
print(f'Boolean mask (x > 0.5):\n{mask}')
print(f'Elements where x > 0.5:\n{x[mask]}')

Boolean mask (x > 0.5):
tensor([[[False,  True,  True,  True, False],
         [False, False, False, False,  True],
         [False,  True, False, False, False],
         [False, False,  True,  True, False]],

        [[False,  True, False, False, False],
         [False,  True,  True,  True, False],
         [False,  True, False, False, False],
         [False, False, False, False, False]],

        [[False,  True, False, False, False],
         [False, False,  True, False, False],
         [False,  True, False,  True, False],
         [False, False,  True, False, False]]])
Elements where x > 0.5:
tensor([0.9433, 0.5270, 1.2860, 0.8512, 0.7496, 0.7858, 1.2082, 0.9461, 0.7608,
        1.2792, 0.6641, 0.6214, 1.0445, 1.5381, 0.5318, 0.6662, 1.5971])


## 2. Tensor Operations

In [44]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print(f'Matrix a: {a}')
print(f'Matrix b: {b}')

Matrix a: tensor([[1, 2],
        [3, 4]])
Matrix b: tensor([[5, 6],
        [7, 8]])


In [45]:
print(f"Matrix multiplication: {torch.matmul(a, b)}")
print(f'Matrix multiplication: {a @ b}')

Matrix multiplication: tensor([[19, 22],
        [43, 50]])
Matrix multiplication: tensor([[19, 22],
        [43, 50]])


In [46]:
print(f'Element-wise multiplication (a * b):\n{a * b}')

Element-wise multiplication (a * b):
tensor([[ 5, 12],
        [21, 32]])


In [47]:
print(f'Transpose of a:\n{a.T}')
print(f'Transpose of a:\n{a.t()}')

Transpose of a:
tensor([[1, 3],
        [2, 4]])
Transpose of a:
tensor([[1, 3],
        [2, 4]])


In [48]:
print(f'Determinant of a: {torch.det(a.float())}')
print(f'Inverse of a:\n{torch.inverse(a.float())}')

Determinant of a: -2.0
Inverse of a:
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


## 2.3 Reduction Operations

In [51]:
x = torch.arange(0, 10, step=1).reshape(2, 5)
print(f"Tensor x:\n{x}")

Tensor x:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [52]:
print(f'Sum of all elements: {torch.sum(x)}')
print(f'Sum of all elements along rows: {x.sum(dim=0)}')
print(f'Sum of all elements along columns: {x.sum(dim=1)}')

Sum of all elements: 45
Sum of all elements along rows: tensor([ 5,  7,  9, 11, 13])
Sum of all elements along columns: tensor([10, 35])


In [55]:
print(f'Mean of all elements: {torch.mean(x.float())}')
print(f'Mean of all elements along rows: {x.float().mean(dim=0)}')
print(f'Mean of all elements along columns: {x.float().mean(dim=1)}')

Mean of all elements: 4.5
Mean of all elements along rows: tensor([2.5000, 3.5000, 4.5000, 5.5000, 6.5000])
Mean of all elements along columns: tensor([2., 7.])


In [59]:
print(f'Max of all elements: {torch.max(x)}')
max_values, max_indicies = x.max(dim=0)
print(f'Max along rows: values={max_values}, indicies={max_indicies}')
print(f'Min of all elements: {torch.min(x)}')

print(f"Product of all elements: {torch.prod(x)}")

Max of all elements: 9
Max along rows: values=tensor([5, 6, 7, 8, 9]), indicies=tensor([1, 1, 1, 1, 1])
Min of all elements: 0
Product of all elements: 0


## 2.4 Reshaping Operations